### ISSUE TITLE
Roadmap Client

### ISSUE THREAD

**Issue by Jokay03J** [Jokay03J/algo-trainer#2]
# Roadmap Client
All feature implemented or planned.

## Teacher
- [ ] Can be created using a provided code
- [ ] Can be logged
- [ ] Can create a student code
- [ ] Can create a classroom
- [ ] Can delete this classrooms
- [ ] Can add a student to a classroom
- [ ] Can remove a student to a classroom
- [ ] Can get all this classroom
- [ ] Can delete a train
- [ ] Can create a train
- [ ] Can access to this classes's trains
- [ ] Can view train student result

## Student
- [ ] Can be logged
- [ ] Can be attached to a teacher with a student code
- [ ] Can get all joined classroom
- [ ] Can access to this classes's trains
- [ ] Can do a train
- [ ] Can save his train result(code used, count retry)
